
pdflatex legal_l1_profile_409.tex
pdflatex legal_l1_profile_419.tex
pdflatex legal_l2_court_profile.tex
pdflatex legal_l3_profile_erp.tex
pdflatex legal_l3_profile_local.tex
pdflatex legal_l3_profile_orgs.tex
pdflatex legal_l3_profile_specialized.tex
pdflatex legal_l3_profile_supreme.tex

pdflatex security-profiles.tex
pdflatex bible_profile.tex
pdflatex chat_profile.tex
pdflatex mail_profile.tex
pdflatex vpn_profile.tex
