EST DEFINITIONS IMPLICIT TAGS ::= BEGIN

    IMPORTS ATTRIBUTE FROM PKIX-CommonTypes-2009 ;

    CsrAttrs ::= SEQUENCE SIZE (0..MAX) OF AttrOrOID
    AttrOrOID ::= CHOICE { oid OBJECT IDENTIFIER, attribute Attribute }
    Attribute ::= SEQUENCE {
        type   ATTRIBUTE.&id,
        values SET SIZE(1..MAX) OF ATTRIBUTE.&Type }

END
