EST DEFINITIONS IMPLICIT TAGS ::= BEGIN
  ATTRIBUTE ::= TYPE-IDENTIFIER
  CsrAttrs ::= SEQUENCE OF AttrOrOID
  AttrOrOID ::= CHOICE { oid OBJECT IDENTIFIER, attribute Attribute }
  Attribute ::= SEQUENCE { type ATTRIBUTE.&id, values SET OF OBJECT IDENTIFIER }
END
