%% Generated by the Erlang ASN.1 compiler. Version: 5.0.21
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CMS-AES-CCM-and-AES-GCM-2009.

-ifndef(_CMS_AES_CCM_AND_AES_GCM_2009_HRL_).
-define(_CMS_AES_CCM_AND_AES_GCM_2009_HRL_, true).

-record('CCMParameters', {
  'aes-nonce',
  'aes-ICVlen' = asn1_DEFAULT
}).

-record('GCMParameters', {
  'aes-nonce',
  'aes-ICVlen' = asn1_DEFAULT
}).

-define('aes', {2,16,840,1,101,3,4,1}).
-define('id-aes128-CCM', {2,16,840,1,101,3,4,1,7}).
-define('id-aes192-CCM', {2,16,840,1,101,3,4,1,27}).
-define('id-aes256-CCM', {2,16,840,1,101,3,4,1,47}).
-define('id-aes128-GCM', {2,16,840,1,101,3,4,1,6}).
-define('id-aes192-GCM', {2,16,840,1,101,3,4,1,26}).
-define('id-aes256-GCM', {2,16,840,1,101,3,4,1,46}).
-endif. %% _CMS_AES_CCM_AND_AES_GCM_2009_HRL_
