%% Generated by the Erlang ASN.1 compiler. Version: 5.2.2
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module DSTU.

-ifndef(_DSTU_HRL_).
-define(_DSTU_HRL_, true).

-record('Certificate', {
  tbsCertificate,
  signatureAlgorithm,
  signatureValue
}).

-record('TBSCertificate', {
  version,
  serialNumber,
  signature,
  issuer,
  validity,
  subject,
  subjectPublicKeyInfo,
  issuerUniqueID = asn1_NOVALUE,
  subjectUniqueID = asn1_NOVALUE,
  extensions
}).

-record('AttributeTypeAndValue', {
  type,
  value
}).

-record('Extension', {
  extnID,
  critical = asn1_DEFAULT,
  extnvalue
}).

-record('Validity', {
  notBefore,
  notAfter
}).

-record('SubjectPublicKeyInfo', {
  algorithm,
  subjectPublicKey
}).

-record('AlgorithmIdentifier', {
  algorithm,
  parameters
}).

-record('DSTU4145Params', {
  definition,
  dke = asn1_NOVALUE
}).

-record('ECBinary', {
  version = asn1_DEFAULT,
  f,
  a,
  b,
  n,
  bp
}).

-record('BinaryField', {
  m,
  p = asn1_NOVALUE
}).

-record('Pentanomial', {
  k,
  j,
  l
}).

-define('id-at', {2,5,4}).
-endif. %% _DSTU_HRL_
