%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module EST.

-ifndef(_EST_HRL_).
-define(_EST_HRL_, true).

-record('Attribute', {
  type,
  values
}).

-endif. %% _EST_HRL_
