%% Generated by the Erlang ASN.1 compiler. Version: 5.0.13
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module KEP.

-ifndef(_KEP_HRL_).
-define(_KEP_HRL_, true).

-record('ContentInfo', {
  contentType,
  content
}).

-record('CrlValidatedID', {
  crlHash,
  crlIdentifier = asn1_NOVALUE
}).

-record('OcspListID', {
  ocspResponses
}).

-record('OcspResponsesID', {
  ocspIdentifier,
  ocspRepHash = asn1_NOVALUE
}).

-record('OtherRevRefs', {
  otherRevRefType,
  otherRevRefs
}).

-record('OcspIdentifier', {
  ocspResponderID,
  producedAt
}).

-record('SignedData', {
  version,
  digestAlgorithms,
  encapContentInfo,
  certificates = asn1_NOVALUE,
  crls = asn1_NOVALUE,
  signerInfos
}).

-record('EncapsulatedContentInfo', {
  eContentType,
  eContent = asn1_NOVALUE
}).

-record('SignerInfo', {
  version,
  sid,
  digestAlgorithm,
  signedAttrs = asn1_NOVALUE,
  signatureAlgorithm,
  signature,
  unsignedAttrs = asn1_NOVALUE
}).

-record('IssuerAndSerialNumber', {
  issuer,
  serialNumber
}).

-record('IssuerSerial', {
  issuer,
  serialNumber
}).

-record('ESSCertIDv2', {
  hashAlgorithm,
  certHash,
  issuerSerial
}).

-record('OtherHashAlgAndValue', {
  hashAlgorithm,
  hashValue
}).

-record('SigPolicyQualifierInfo', {
  sigPolicyQualifierId,
  sigQualifier
}).

-record('SignaturePolicyId', {
  sigPolicyId,
  sigPolicyHash = asn1_NOVALUE
}).

-record('Attribute', {
  attrType,
  attrValues
}).

-record('SigningCertificateV2', {
  certs,
  policies = asn1_NOVALUE
}).

-record('CrlOcspRef', {
  crlids = asn1_NOVALUE,
  ocspids = asn1_NOVALUE,
  otherRev = asn1_NOVALUE
}).

-record('CrlIdentifier', {
  crlissuer,
  crlIssuedTime,
  crlNumber = asn1_NOVALUE
}).

-record('BasicOCSPResponse', {
  tbsResponseData,
  signatureAlgorithm,
  signature,
  certs = asn1_NOVALUE
}).

-record('ResponseData', {
  version = asn1_DEFAULT,
  responderID,
  producedAt,
  responses,
  responseExtensions = asn1_NOVALUE
}).

-record('CertID', {
  hashAlgorithm,
  issuerNameHash,
  issuerKeyHash,
  serialNumber
}).

-record('RevokedInfo', {
  revocationTime,
  revocationReason = asn1_NOVALUE
}).

-record('SingleResponse', {
  certID,
  certStatus,
  thisUpdate,
  nextUpdate = asn1_NOVALUE,
  singleExtensions = asn1_NOVALUE
}).

-record('RevocationValues', {
  crlVals = asn1_NOVALUE,
  ocspVals = asn1_NOVALUE,
  otherRevVals = asn1_NOVALUE
}).

-record('OtherRevVals', {
  otherRevValType
}).

-record('CRLListID', {
  crls
}).

-record('MessageImprint', {
  hashAlgorithm,
  hashedMessage
}).

-record('TimeStampReq', {
  version,
  messageImprint,
  reqPolicy = asn1_NOVALUE,
  nonce = asn1_NOVALUE,
  certReq = asn1_DEFAULT,
  extensions = asn1_NOVALUE
}).

-record('INSTANCE OF', {
  'type-id',
  value
}).

-define('id-data', {1,2,840,113549,1,7,1}).
-define('id-signedData', {1,2,840,113549,1,7,2}).
-define('id-contentType', {1,2,840,113549,1,9,3}).
-define('id-messageDigest', {1,2,840,113549,1,9,4}).
-define('id-signingTime', {1,2,840,113549,1,9,5}).
-define('id-aa-signTSToken', {1,2,840,113549,1,9,16,2,14}).
-define('id-aa-ets-sigPolicyId', {1,2,840,113549,1,9,16,2,15}).
-define('id-aa-ets-ContentTS', {1,2,840,113549,1,9,16,2,20}).
-define('id-aa-ets-certRefs', {1,2,840,113549,1,9,16,2,21}).
-define('id-aa-ets-revocationRefs', {1,2,840,113549,1,9,16,2,22}).
-define('id-aa-ets-certValues', {1,2,840,113549,1,9,16,2,23}).
-define('id-aa-ets-revoValues', {1,2,840,113549,1,9,16,2,24}).
-define('id-aa-signingCertV2', {1,2,840,113549,1,9,16,2,47}).
-define('id-spq-ets-uri', {1,2,840,113549,1,9,16,5,1}).
-define('id-spq-ets-unotice', {1,2,840,113549,1,9,16,5,2}).
-define('gost34311', {1,2,804,2,1,1,1,1,2,1}).
-endif. %% _KEP_HRL_
