%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKCS-1.

-ifndef(_PKCS_1_HRL_).
-define(_PKCS_1_HRL_, true).

-record('AlgorithmIdentifier-PKCS1', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('HashAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('MaskGenAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('PSourceAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('RSAPublicKey', {
  modulus,
  publicExponent
}).

-record('RSAPrivateKey', {
  version,
  modulus,
  publicExponent,
  privateExponent,
  prime1,
  prime2,
  exponent1,
  exponent2,
  coefficient,
  otherPrimeInfos = asn1_NOVALUE
}).

-record('OtherPrimeInfo', {
  prime,
  exponent,
  coefficient
}).

-record('RSAES-OAEP-params', {
  hashAlgorithm = asn1_DEFAULT,
  maskGenAlgorithm = asn1_DEFAULT,
  pSourceAlgorithm = asn1_DEFAULT
}).

-record('RSAES-AlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('RSASSA-PSS-params', {
  hashAlgorithm = asn1_DEFAULT,
  maskGenAlgorithm = asn1_DEFAULT,
  saltLength = asn1_DEFAULT,
  trailerField = asn1_DEFAULT
}).

-record('RSASSA-AlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('DigestInfo', {
  digestAlgorithm,
  digest
}).

-record('DigestAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-define('pkcs-1', {1,2,840,113549,1,1}).
-define('rsaEncryption', {1,2,840,113549,1,1,1}).
-define('id-RSAES-OAEP', {1,2,840,113549,1,1,7}).
-define('id-pSpecified', {1,2,840,113549,1,1,9}).
-define('id-RSASSA-PSS', {1,2,840,113549,1,1,10}).
-define('md2WithRSAEncryption', {1,2,840,113549,1,1,2}).
-define('md5WithRSAEncryption', {1,2,840,113549,1,1,4}).
-define('sha1WithRSAEncryption', {1,2,840,113549,1,1,5}).
-define('sha224WithRSAEncryption', {1,2,840,113549,1,1,14}).
-define('sha256WithRSAEncryption', {1,2,840,113549,1,1,11}).
-define('sha384WithRSAEncryption', {1,2,840,113549,1,1,12}).
-define('sha512WithRSAEncryption', {1,2,840,113549,1,1,13}).
-define('sha512-224WithRSAEncryption', {1,2,840,113549,1,1,15}).
-define('sha512-256WithRSAEncryption', {1,2,840,113549,1,1,16}).
-define('sha-1WithRSAEncryption', {1,3,14,3,2,29}).
-define('id-sha1', {1,3,14,3,2,26}).
-define('id-md2', {1,2,840,113549,2,2}).
-define('id-md5', {1,2,840,113549,2,5}).
-define('id-hmacWithSHA224', {1,2,840,113549,2,8}).
-define('id-hmacWithSHA256', {1,2,840,113549,2,9}).
-define('id-hmacWithSHA384', {1,2,840,113549,2,10}).
-define('id-hmacWithSHA512', {1,2,840,113549,2,11}).
-define('id-sha224', {2,16,840,1,101,3,4,2,4}).
-define('id-sha256', {2,16,840,1,101,3,4,2,1}).
-define('id-sha384', {2,16,840,1,101,3,4,2,2}).
-define('id-sha512', {2,16,840,1,101,3,4,2,3}).
-define('id-mgf1', {1,2,840,113549,1,1,8}).
-define('sha1', {'HashAlgorithm',{1,3,14,3,2,26},'NULL'}).
-define('mgf1SHA1', {'MaskGenAlgorithm',{1,2,840,113549,1,1,8},{'Externalvaluereference',220,'PKCS-1',sha1}}).
-define('pSpecifiedEmpty', {'PSourceAlgorithm',{1,2,840,113549,1,1,9},<<>>}).
-define('emptyString', <<>>).
-define('rSAES-OAEP-Default-Identifier', {'RSAES-AlgorithmIdentifier',{1,2,840,113549,1,1,7},{'RSAES-OAEP-params',{'Externalvaluereference',320,'PKCS-1',sha1},{'Externalvaluereference',321,'PKCS-1',mgf1SHA1},{'Externalvaluereference',322,'PKCS-1',pSpecifiedEmpty}}}).
-define('rSASSA-PSS-Default-Identifier', {'RSASSA-AlgorithmIdentifier',{1,2,840,113549,1,1,10},{'RSASSA-PSS-params',{'Externalvaluereference',355,'PKCS-1',sha1},{'Externalvaluereference',356,'PKCS-1',mgf1SHA1},20,1}}).
-endif. %% _PKCS_1_HRL_
