%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKIX1-PSS-OAEP-Algorithms-2009.

-ifndef(_PKIX1_PSS_OAEP_ALGORITHMS_2009_HRL_).
-define(_PKIX1_PSS_OAEP_ALGORITHMS_2009_HRL_, true).

-record('HashAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('MaskGenAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('PSourceAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('RSASSA-PSS-params', {
  hashAlgorithm = asn1_DEFAULT,
  maskGenAlgorithm = asn1_DEFAULT,
  saltLength = asn1_DEFAULT,
  trailerField = asn1_DEFAULT
}).

-record('RSAES-OAEP-params', {
  hashFunc = asn1_DEFAULT,
  maskGenFunc = asn1_DEFAULT,
  pSourceFunc = asn1_DEFAULT
}).

-define('sha224WithRSAEncryption', {1,2,840,113549,1,1,14}).
-define('sha256WithRSAEncryption', {1,2,840,113549,1,1,11}).
-define('sha384WithRSAEncryption', {1,2,840,113549,1,1,12}).
-define('sha512WithRSAEncryption', {1,2,840,113549,1,1,13}).
-define('pkcs-1', {1,2,840,113549,1,1}).
-define('id-RSAES-OAEP', {1,2,840,113549,1,1,7}).
-define('id-mgf1', {1,2,840,113549,1,1,8}).
-define('id-pSpecified', {1,2,840,113549,1,1,9}).
-define('id-RSASSA-PSS', {1,2,840,113549,1,1,10}).
-define('id-sha224', {2,16,840,1,101,3,4,2,4}).
-define('id-sha256', {2,16,840,1,101,3,4,2,1}).
-define('id-sha384', {2,16,840,1,101,3,4,2,2}).
-define('id-sha512', {2,16,840,1,101,3,4,2,3}).
-define('nullOctetString', <<>>).
-define('nullParameters', 'NULL').
-define('sha1Identifier', {'HashAlgorithm',{1,3,14,3,2,26},'NULL'}).
-define('mgf1SHA1', {'MaskGenAlgorithm',{1,2,840,113549,1,1,8},{'Externalvaluereference',248,'PKIX1-PSS-OAEP-Algorithms-2009',sha1Identifier}}).
-define('pSpecifiedEmpty', {'PSourceAlgorithm',{1,2,840,113549,1,1,9},<<>>}).
-endif. %% _PKIX1_PSS_OAEP_ALGORITHMS_2009_HRL_
