%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKIXAlgs-2009.

-ifndef(_PKIXALGS_2009_HRL_).
-define(_PKIXALGS_2009_HRL_, true).

-record('RSAPublicKey', {
  modulus,
  publicExponent
}).

-record('DSA-Params', {
  p,
  q,
  g
}).

-record('DomainParameters', {
  p,
  g,
  q,
  j = asn1_NOVALUE,
  validationParams = asn1_NOVALUE
}).

-record('ValidationParams', {
  seed,
  pgenCounter
}).

-record('DSA-Sig-Value', {
  r,
  s
}).

-record('ECDSA-Sig-Value', {
  r,
  s
}).

-define('rsaEncryption', {1,2,840,113549,1,1,1}).
-define('id-dsa', {1,2,840,10040,4,1}).
-define('dhpublicnumber', {1,2,840,10046,2,1}).
-define('id-keyExchangeAlgorithm', {2,16,840,1,101,2,1,1,22}).
-define('id-ecPublicKey', {1,2,840,10045,2,1}).
-define('id-ecDH', {1,3,132,1,12}).
-define('id-ecMQV', {1,3,132,1,13}).
-define('secp192r1', {1,2,840,10045,3,1,1}).
-define('sect163k1', {1,3,132,0,1}).
-define('sect163r2', {1,3,132,0,15}).
-define('secp224r1', {1,3,132,0,33}).
-define('sect233k1', {1,3,132,0,26}).
-define('sect233r1', {1,3,132,0,27}).
-define('secp256r1', {1,2,840,10045,3,1,7}).
-define('sect283k1', {1,3,132,0,16}).
-define('sect283r1', {1,3,132,0,17}).
-define('secp384r1', {1,3,132,0,34}).
-define('sect409k1', {1,3,132,0,36}).
-define('sect409r1', {1,3,132,0,37}).
-define('secp521r1', {1,3,132,0,35}).
-define('sect571k1', {1,3,132,0,38}).
-define('sect571r1', {1,3,132,0,39}).
-define('md2WithRSAEncryption', {1,2,840,113549,1,1,2}).
-define('md5WithRSAEncryption', {1,2,840,113549,1,1,4}).
-define('sha1WithRSAEncryption', {1,2,840,113549,1,1,5}).
-define('dsa-with-sha1', {1,2,840,10040,4,3}).
-define('dsa-with-sha224', {2,16,840,1,101,3,4,3,1}).
-define('dsa-with-sha256', {2,16,840,1,101,3,4,3,2}).
-define('ecdsa-with-SHA1', {1,2,840,10045,4,1}).
-define('ecdsa-with-SHA224', {1,2,840,10045,4,3,1}).
-define('ecdsa-with-SHA256', {1,2,840,10045,4,3,2}).
-define('ecdsa-with-SHA384', {1,2,840,10045,4,3,3}).
-define('ecdsa-with-SHA512', {1,2,840,10045,4,3,4}).
-define('id-md2', {1,2,840,113549,2,2}).
-define('id-md5', {1,2,840,113549,2,5}).
-define('id-sha1', {1,3,14,3,2,26}).
-endif. %% _PKIXALGS_2009_HRL_
