%% Generated by the Erlang ASN.1 compiler. Version: 5.0.17
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKIX-CommonTypes-2009.

-ifndef(_PKIX_COMMONTYPES_2009_HRL_).
-define(_PKIX_COMMONTYPES_2009_HRL_, true).

-record('AttributeSet', {
  type,
  values
}).

-record('SingleAttribute', {
  type,
  value
}).

-record('Extension', {
  extnID,
  critical = asn1_DEFAULT,
  extnValue
}).

-record('SecurityCategory', {
  type,
  value
}).

-endif. %% _PKIX_COMMONTYPES_2009_HRL_
