%% Generated by the Erlang ASN.1 compiler. Version: 5.0.21
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CMSAesRsaesOaep-2009.

-ifndef(_CMSAESRSAESOAEP_2009_HRL_).
-define(_CMSAESRSAESOAEP_2009_HRL_, true).

-define('aes', {2,16,840,1,101,3,4,1}).
-define('id-aes128-CBC', {2,16,840,1,101,3,4,1,2}).
-define('id-aes192-CBC', {2,16,840,1,101,3,4,1,22}).
-define('id-aes256-CBC', {2,16,840,1,101,3,4,1,42}).
-define('id-aes128-wrap', {2,16,840,1,101,3,4,1,5}).
-define('id-aes192-wrap', {2,16,840,1,101,3,4,1,25}).
-define('id-aes256-wrap', {2,16,840,1,101,3,4,1,45}).
-endif. %% _CMSAESRSAESOAEP_2009_HRL_
