name: mix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25.x', '26.x', '27.x', '28.x']
        include:
          - otp: '25.x'
            elixir: '1.17.x'
          - otp: '26.x'
            elixir: '1.17.x'
          - otp: '27.x'
            elixir: '1.18.x'
          - otp: '28.x'
            elixir: '1.19.x'
    steps:
    - uses: actions/checkout@v4
    - name: System packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          pkg-config \
          libtss2-dev \
          libtss2-esys-3.0.2-0 \
          libtss2-rc0
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.clean --unused
    - name: Compilation
      run: mix compile
    - name: Tests
      run: mix test
